[supabase]
url = "https://cjrxecnmkszrnkirxgqi.supabase.co"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqcnhlY25ta3N6cm5raXJ4Z3FpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NDk1MTU5NywiZXhwIjoyMDcwNTI3NTk3fQ.a2coqnq9Si2sEeSd-SRJfx2aPJKmIiU6_32TTtMFAzg"
